drop table if exists loan CASCADE;
create table loan
(
    id                  BIGINT generated by default as identity,
    loan_amount         BIGINT NOT NULL,
    interest_rate       DOUBLE PRECISION NOT NULL,
    loan_type           VARCHAR(50) NOT NULL,
    loan_term           INTEGER NOT NULL,
    loan_date           VARCHAR(50) NOT NULL,
    primary key (id)
);

drop table if exists schedule CASCADE;
create table schedule
(
    id                  BIGINT generated by default as identity,
    loan_id             BIGINT NOT NULL,
    payment_count       INTEGER NOT NULL,
    payment_date        VARCHAR(50) NOT NULL,
    monthly_payment     BIGINT NOT NULL,
    monthly_principal   BIGINT NOT NULL,
    monthly_interest    BIGINT NOT NULL,
    loan_balance        BIGINT NOT NULL,
    interest_balance    BIGINT NOT NULL,
    primary key (id)
);

alter table schedule
add foreign key (loan_id)
references loan (id);